config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :departments
  resources :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# EmployeesController
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  def index
    grid = EmployeesGrid.new(params[:employees_grid]) do |scope|
      scope.includes(:department).page(params[:page]).per_page(5)
    end

    render :index, locals: { employees_grid: grid }
  end

  def new
    form = EmployeeForm.new(Employee.new)
    form.prepopulate!
    render :new, locals: { form: form, department_collection: department_collection }
  end

  def create
    form = EmployeeForm.new(Employee.new)
    form.call(params[:employees]) do
      flash[:success] = 'Запись успешно добавлена!'
      return redirect_to edit_employee_path(form.model.id)
    end

    flash[:error] = 'Не все обязательные поля заполнены!'
    form.prepopulate!
    render :new, locals: { form: form, department_collection: department_collection }
  end

  def edit
    form = EmployeeForm.new(employee)
    form.prepopulate!
    render :edit, locals: { form: form, department_collection: department_collection }
  end

  def update
    form = EmployeeForm.new(employee)
    form.call(params[:employees]) do
      flash[:success] = 'Запись успешно обновлена!'
      return redirect_to edit_employee_path(form.model.id)
    end

    flash[:error] = 'Не все обязательные поля заполнены!'
    form.prepopulate!
    render :edit, locals: { form: form, department_collection: department_collection }
  end

  def destroy
    if employee.present?
      employee.destroy!
      flash[:success] = 'Запись успешно удалена!'
    else
      flash[:error] = 'Запись не найдена!'
    end
    redirect_to employees_path
  end

  private

  def employee
    @employee ||= Employee.find(params[:id])
  end

  def department_collection
    @department_collection ||= Department.pluck(:title, :id)
  end
end

app/views/employees/_form.html.erb
<%= simple_form_for form, as: :employees, url: url do |f| %>
  <div class="ibox">
    <div class="ibox-content">
      <%= f.input :name, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
      <%= f.input :active, as: :boolean, label: 'Active' %>
      <%= f.input :department_id, label: 'Department',
                collection: department_collection,
                prompt: false,
                label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to "Back", employees_path, class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/employees/_grid_actions.html.erb
<div class="btn-group">
  <%= link_to(edit_employee_path(employee.id),
              class: 'btn btn-white btn-xs') do %>
      <%= fa_icon('pencil') %>
      Edit
  <% end %>

  <%= link_to employee_path(employee.id),
              class: 'btn btn-white btn-xs',
              data: {confirm: 'Are you sure?', method: :delete} do %>
      <%= fa_icon('trash') %>
      Delete
  <% end %>
</div>

app/views/employees/edit.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-content text-center p-md">
    <h2>Edit employee</h2>
  </div>
  <div class="ibox-content">
    <%= render 'form', form: form, url: employee_path(form.model.id), department_collection: department_collection %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Employees</h5>
    <ol class="search_field">
     <%= datagrid_form_for employees_grid,
                        method: :get,
                        url: employees_path %>
</ol>
<br class="clear">
    <div class="text-right">
      <%= link_to 'Add employee', new_employee_path,
                  class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="ibox-content">
    <%= datagrid_table(employees_grid,
                       html: {class: 'table table-hover datagrid'}) %>
    <%= will_paginate employees_grid.assets %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-content text-center p-md">
    <h2>New employee</h2>
  </div>
  <div class="ibox-content">
    <%= render 'form', form: form, url: employees_path, department_collection: department_collection %>
  </div>
</div>