config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :departments
  resources :employees
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/controllers/departments_controller.rb
# frozen_string_literal: true

# DepartmentsController
class DepartmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    grid = DepartmentsGrid.new(params[:departments_grid]) do |scope|
      scope.page(params[:page]).per_page(5)
    end

    render :index, locals: { departments_grid: grid }
  end

  def new
    form = DepartmentForm.new(Department.new)
    form.prepopulate!
    render :new, locals: { form: form }
  end

  def create
    form = DepartmentForm.new(Department.new)
    form.call(params[:departments]) do
      flash[:success] = 'Запись успешно добавлена!'
      return redirect_to edit_department_path(form.model.id)
    end

    flash[:error] = 'Не все обязательные поля заполнены!'
    form.prepopulate!
    render :new, locals: { form: form }
  end

  def edit
    form = DepartmentForm.new(department)
    form.prepopulate!
    render :edit, locals: { form: form }
  end

  def update
    form = DepartmentForm.new(department)
    form.call(params[:departments]) do
      flash[:success] = 'Запись успешно обновлена!'
      return redirect_to edit_department_path(form.model.id)
    end

    flash[:error] = 'Не все обязательные поля заполнены!'
    form.prepopulate!
    render :edit, locals: { form: form }
  end

  def destroy
    if department.present?
      department.destroy!
      flash[:success] = 'Запись успешно удалена!'
    else
      flash[:error] = 'Запись не найдена!'
    end
    redirect_to departments_path
  end

  private

  def department
    @department ||= Department.find(params[:id])
  end
end

app/views/departments/_form.html.erb
<%= simple_form_for form, as: :departments, url: url do |f| %>
  <div class="ibox">
    <div class="ibox-content">
      <%= f.input :title, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to "Back", departments_path, class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/departments/_grid_actions.html.erb
<div class="btn-group">
  <%= link_to(edit_department_path(department.id),
              class: 'btn btn-white btn-xs') do %>
      <%= fa_icon('pencil') %>
      Edit
  <% end %>

  <%= link_to department_path(department.id),
              class: 'btn btn-white btn-xs',
              data: {confirm: 'Are you sure?', method: :delete} do %>
      <%= fa_icon('trash') %>
      Delete
  <% end %>
</div>

app/views/departments/edit.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-content text-center p-md">
    <h2>Edit department</h2>
  </div>
  <div class="ibox-content">
    <%= render 'form', form: form, url: department_path(form.model.id) %>
  </div>
</div>

app/views/departments/index.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Departments</h5>
    <ol class="search_field">
 <%= datagrid_form_for departments_grid,
                    method: :get,
                    url: departments_path %>
</ol>
    <div class="text-right">
      <%= link_to 'Add department', new_department_path,
                  class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="ibox-content">
    <%= datagrid_table(departments_grid,
                       html: {class: 'table table-hover datagrid'}) %>
    <%= will_paginate departments_grid.assets %>
  </div>
</div>

app/views/departments/new.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-content text-center p-md">
    <h2>New department</h2>
  </div>
  <div class="ibox-content">
    <%= render 'form', form: form, url: departments_path %>
  </div>
</div>